version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'project_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/var/log/mysql
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  mysql_data:
    driver: local