version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'project_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/var/log/mysql
      - /usr/local/var/mysql:/var/lib/mysql
#     networks:
#       - mysql-network

# networks:
#   mysql-network:
#     driver: bridge